name: coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install libclang
      run: |
        sudo apt-get -y install libclang1-9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    - name: Test coverage with coerage and pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov-fail-under=85 --cov=cnaming --cov-report term --cov-report annotate:cov tests/*
    - name: Print missing coverage
      if: always()
      run: |
        grep -2nr "^!" cov/
